markdown: kramdown

title: Palmer Lab @ University of Maryland

url: '//akottkam.github.io'
production_url: 'https://akottkam.github.io'

permalink: "/news/:year-:month-:day-:title/"

author:
    name: Anna K.  
    email: akottkam@terpmail.umd
    github: akottkam
    twitter: akottkamper
    gravatar: 

#comments:
#    provider: disqusasdf
#    disqus: yannickwurm
#        short_name: "yannickwurm"
#    disqus_name: "adsf"

#analytics:
#    provider: google 
#    google: 
#        tracking_id: 'UA-471841-2'
#        domain: 'wurmlab.github.io'

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'Rakefile']

gems:
  - jekyll-redirect-from
